// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnmpxvinczzgzqnzcrim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdubXB4dmluY3p6Z3pxbnpjcmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjY1MjksImV4cCI6MjA3MzYwMjUyOX0.w6sl94vCmtZj51-DZuXlpLnqful_cKc5LRjvzBurmOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});